# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusUpdate',
            new_name='ProfileFeedItem',
        ),
    ]
